export interface Remedy {
  key: string;
  title: string;
  icon: string;
  category: "morning" | "diet" | "evening" | "sleep" | "lifestyle";
  duration_minutes: number;
  is_premium: boolean;
  applicable_to: Array<"face" | "hair" | "both">;
  skin_types: Array<"oily" | "dry" | "combination" | "normal" | "all">;
  severity: Array<"mild" | "moderate" | "serious">;
  season: "monsoon" | "summer" | "winter" | null;
  description: string;
}

export const REMEDY_LIBRARY: Remedy[] = [
  // ─── FACE - MORNING ───
  {
    key: "neem_paste",
    title: "Apply Neem Paste",
    icon: "Leaf",
    category: "morning",
    duration_minutes: 10,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["oily", "combination"],
    severity: ["mild", "moderate", "serious"],
    season: null,
    description: "Mix neem powder with rose water into a paste. Apply on affected areas for 10 minutes then rinse.",
  },
  {
    key: "aloe_vera_gel",
    title: "Aloe Vera Gel Soothing",
    icon: "Plant",
    category: "morning",
    duration_minutes: 5,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Apply fresh aloe vera gel directly from the plant to your face. Leave on as a light moisturiser.",
  },
  {
    key: "rose_water_toner",
    title: "Rose Water Toner",
    icon: "Flower",
    category: "morning",
    duration_minutes: 3,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["dry", "normal", "combination"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Spray rose water on a cotton pad and gently wipe your face to balance pH and hydrate.",
  },
  {
    key: "ice_cube_massage",
    title: "Ice Cube Massage",
    icon: "Snowflake",
    category: "morning",
    duration_minutes: 5,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["oily", "combination"],
    severity: ["mild", "moderate"],
    season: "summer",
    description: "Wrap an ice cube in a cloth and gently massage your face in circular motions to reduce pores.",
  },
  {
    key: "turmeric_honey_mask",
    title: "Turmeric + Honey Mask",
    icon: "Star",
    category: "morning",
    duration_minutes: 15,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["oily", "combination", "normal"],
    severity: ["moderate", "serious"],
    season: null,
    description: "Mix 1/4 tsp turmeric with 1 tsp raw honey. Apply evenly on face, wait 15 minutes and rinse gently.",
  },
  {
    key: "multani_mitti_pack",
    title: "Multani Mitti Clay Pack",
    icon: "Circle",
    category: "morning",
    duration_minutes: 15,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["oily", "combination"],
    severity: ["moderate", "serious"],
    season: null,
    description: "Mix multani mitti with rose water to a paste. Apply and let dry for 15 minutes, then rinse.",
  },
  {
    key: "green_tea_steam",
    title: "Green Tea Steam",
    icon: "Coffee",
    category: "morning",
    duration_minutes: 10,
    is_premium: true,
    applicable_to: ["face"],
    skin_types: ["all"],
    severity: ["moderate", "serious"],
    season: "winter",
    description: "Brew green tea, pour into a bowl, drape a towel over your head and steam your face for 5–10 minutes.",
  },
  {
    key: "castor_oil_spot",
    title: "Castor Oil Spot Treatment",
    icon: "Droplet",
    category: "morning",
    duration_minutes: 5,
    is_premium: true,
    applicable_to: ["face"],
    skin_types: ["dry", "normal"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Dab a tiny amount of castor oil on spots or dry patches using a cotton swab overnight.",
  },
  {
    key: "cucumber_eye_soothe",
    title: "Cucumber Eye Soothe",
    icon: "Eye",
    category: "morning",
    duration_minutes: 10,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["all"],
    severity: ["mild"],
    season: "summer",
    description: "Place chilled cucumber slices over closed eyes for 10 minutes to reduce puffiness.",
  },
  {
    key: "face_clean_water",
    title: "Gentle Cold Water Cleanse",
    icon: "Drop",
    category: "morning",
    duration_minutes: 3,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: null,
    description: "Splash your face with cold water (no soap) in the morning to remove overnight oil buildup.",
  },
  // ─── FACE - EVENING ───
  {
    key: "double_cleanse",
    title: "Double Cleanse Routine",
    icon: "Sparkle",
    category: "evening",
    duration_minutes: 10,
    is_premium: true,
    applicable_to: ["face"],
    skin_types: ["oily", "combination"],
    severity: ["moderate", "serious"],
    season: null,
    description: "First cleanse with micellar water, then use a gentle face wash to fully remove the day's grime.",
  },
  {
    key: "besan_scrub",
    title: "Besan Face Scrub",
    icon: "SmileyWink",
    category: "evening",
    duration_minutes: 10,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["oily", "combination", "normal"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Mix besan (gram flour) with milk or rose water into a paste. Scrub gently in circles, then rinse.",
  },
  {
    key: "retinol_serum",
    title: "Retinol Serum Night Apply",
    icon: "Moon",
    category: "evening",
    duration_minutes: 3,
    is_premium: true,
    applicable_to: ["face"],
    skin_types: ["normal", "combination"],
    severity: ["moderate", "serious"],
    season: null,
    description: "Apply a pea-size amount of retinol serum on clean skin before sleeping for cell renewal.",
  },
  {
    key: "papaya_enzyme_mask",
    title: "Papaya Enzyme Mask",
    icon: "Palette",
    category: "evening",
    duration_minutes: 15,
    is_premium: true,
    applicable_to: ["face"],
    skin_types: ["dry", "normal", "combination"],
    severity: ["mild", "moderate"],
    season: "summer",
    description: "Mash ripe papaya and apply on clean face. Wait 15 minutes — natural enzymes gently exfoliate.",
  },
  {
    key: "overnight_aloe",
    title: "Overnight Aloe Treatment",
    icon: "MoonStars",
    category: "evening",
    duration_minutes: 3,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Apply a thin layer of pure aloe vera gel on your face before sleeping for overnight healing.",
  },
  // ─── HAIR - MORNING ───
  {
    key: "coconut_oil_massage",
    title: "Coconut Oil Scalp Massage",
    icon: "HandWaving",
    category: "morning",
    duration_minutes: 15,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: null,
    description: "Warm 2 tbsp coconut oil and massage gently into scalp in circular motions for 15 minutes, then leave for 1 hour.",
  },
  {
    key: "onion_juice",
    title: "Onion Juice Application",
    icon: "CircleHalf",
    category: "morning",
    duration_minutes: 30,
    is_premium: true,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["moderate", "serious"],
    season: null,
    description: "Blend and strain onion juice. Apply directly to scalp with a cotton ball. Leave 30 minutes then shampoo.",
  },
  {
    key: "amla_powder_pack",
    title: "Amla Powder Hair Pack",
    icon: "Acorn",
    category: "morning",
    duration_minutes: 30,
    is_premium: true,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["moderate", "serious"],
    season: null,
    description: "Mix amla powder with warm water or coconut oil. Apply to scalp and hair lengths, leave 30 minutes.",
  },
  {
    key: "bhringraj_oil",
    title: "Bhringraj Oil Treatment",
    icon: "Flower",
    category: "morning",
    duration_minutes: 20,
    is_premium: true,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["moderate", "serious"],
    season: null,
    description: "Warm bhringraj oil and massage into scalp. Cover with a warm towel for 20 minutes before washing.",
  },
  {
    key: "egg_mask_hair",
    title: "Egg Protein Mask",
    icon: "Egg",
    category: "morning",
    duration_minutes: 20,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Whisk 1–2 eggs and apply to damp hair. Leave for 20 minutes then rinse with cool water.",
  },
  {
    key: "curd_fenugreek_mask",
    title: "Curd + Fenugreek Mask",
    icon: "GrainSlash",
    category: "morning",
    duration_minutes: 30,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: null,
    description: "Soak fenugreek seeds overnight, blend with curd. Apply to scalp, leave 30 minutes then rinse.",
  },
  {
    key: "scalp_massage_dry",
    title: "Dry Scalp Massage",
    icon: "Brain",
    category: "morning",
    duration_minutes: 5,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild"],
    season: null,
    description: "Use fingertips (not nails) to gently massage your scalp for 5 minutes to boost circulation.",
  },
  {
    key: "rice_water_rinse",
    title: "Rice Water Hair Rinse",
    icon: "Grain",
    category: "morning",
    duration_minutes: 20,
    is_premium: true,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Soak rice in water for 2 hours, strain. After shampooing, pour rice water through hair, leave 20 min, rinse.",
  },
  {
    key: "aloe_scalp_gel",
    title: "Aloe Vera Scalp Gel",
    icon: "Plant",
    category: "morning",
    duration_minutes: 30,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: "summer",
    description: "Apply fresh aloe vera gel directly to scalp and hair lengths. Leave for 30 minutes before rinsing.",
  },
  // ─── DIET ───
  {
    key: "reduce_sugar",
    title: "Skip Added Sugar Today",
    icon: "CandyOff",
    category: "diet",
    duration_minutes: 0,
    is_premium: false,
    applicable_to: ["face", "hair", "both"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: null,
    description: "Avoid sweets, sodas, and packaged foods with added sugar. High sugar spikes insulin and worsens breakouts.",
  },
  {
    key: "reduce_dairy",
    title: "Go Dairy-Free Today",
    icon: "Prohibit",
    category: "diet",
    duration_minutes: 0,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["oily", "combination"],
    severity: ["moderate", "serious"],
    season: null,
    description: "Avoid milk, paneer, and curd today. Dairy can trigger hormonal breakouts in some people.",
  },
  {
    key: "zinc_foods",
    title: "Eat Zinc-Rich Foods",
    icon: "ForkKnife",
    category: "diet",
    duration_minutes: 0,
    is_premium: false,
    applicable_to: ["face", "hair", "both"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: null,
    description: "Eat pumpkin seeds, chickpeas, or lentils today. Zinc reduces inflammation and supports hair growth.",
  },
  {
    key: "water_morning",
    title: "3 Glasses Water Before 10am",
    icon: "Drop",
    category: "diet",
    duration_minutes: 0,
    is_premium: false,
    applicable_to: ["face", "hair", "both"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: null,
    description: "Drink 3 glasses of plain water before 10am to flush toxins and hydrate your skin from inside.",
  },
  {
    key: "green_tea_drink",
    title: "Drink 2 Cups Green Tea",
    icon: "Coffee",
    category: "diet",
    duration_minutes: 0,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Replace one chai and one coffee with green tea today. Antioxidants reduce oxidative stress on skin.",
  },
  {
    key: "avoid_fried",
    title: "No Fried Food Today",
    icon: "X",
    category: "diet",
    duration_minutes: 0,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["oily", "combination"],
    severity: ["moderate", "serious"],
    season: null,
    description: "Avoid samosas, chips, and any deep-fried items. Excess oil in diet shows up on your skin.",
  },
  {
    key: "biotin_foods",
    title: "Eat Biotin-Rich Foods",
    icon: "Egg",
    category: "diet",
    duration_minutes: 0,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: null,
    description: "Include eggs, almonds, sweet potatoes or bananas in today's meals. Biotin is critical for hair growth.",
  },
  {
    key: "iron_rich_foods",
    title: "Add Iron-Rich Foods",
    icon: "Barbell",
    category: "diet",
    duration_minutes: 0,
    is_premium: true,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["moderate", "serious"],
    season: null,
    description: "Eat spinach, rajma, or dates today. Iron deficiency is one of the top causes of hair fall.",
  },
  {
    key: "omega3_foods",
    title: "Omega-3 Rich Meal",
    icon: "Fish",
    category: "diet",
    duration_minutes: 0,
    is_premium: true,
    applicable_to: ["face", "hair", "both"],
    skin_types: ["dry", "normal"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Add walnuts, flaxseeds, or fatty fish to today's diet for essential fatty acids that nourish skin and hair.",
  },
  {
    key: "coconut_water",
    title: "Drink Coconut Water",
    icon: "Drop",
    category: "diet",
    duration_minutes: 0,
    is_premium: false,
    applicable_to: ["face", "hair", "both"],
    skin_types: ["all"],
    severity: ["mild"],
    season: "summer",
    description: "Drink one glass of fresh coconut water to replenish electrolytes and deeply hydrate skin in the heat.",
  },
  {
    key: "protein_rich_meal",
    title: "High-Protein Meal Today",
    icon: "Barbell",
    category: "diet",
    duration_minutes: 0,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["moderate", "serious"],
    season: null,
    description: "Ensure one meal has dal, paneer, eggs, or chicken. Hair is made of protein — deficiency causes shedding.",
  },
  // ─── SLEEP ───
  {
    key: "change_pillowcase",
    title: "Change Your Pillowcase",
    icon: "Bed",
    category: "sleep",
    duration_minutes: 5,
    is_premium: false,
    applicable_to: ["face", "hair", "both"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: null,
    description: "Swap your pillowcase tonight. Pillowcases accumulate oil and bacteria which transfers to your face every night.",
  },
  {
    key: "elevate_pillow",
    title: "Elevate Pillow Slightly",
    icon: "ArrowUp",
    category: "sleep",
    duration_minutes: 2,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Sleep with your head slightly elevated (add an extra pillow) to reduce facial puffiness overnight.",
  },
  {
    key: "no_phone_before_sleep",
    title: "No Phone 30 Min Before Sleep",
    icon: "PhoneSlash",
    category: "sleep",
    duration_minutes: 30,
    is_premium: false,
    applicable_to: ["face", "hair", "both"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: null,
    description: "Put your phone away 30 minutes before bed. Blue light disrupts melatonin and impairs overnight skin repair.",
  },
  {
    key: "silk_pillowcase",
    title: "Switch to Silk Pillowcase",
    icon: "Star",
    category: "sleep",
    duration_minutes: 5,
    is_premium: true,
    applicable_to: ["face", "hair", "both"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Silk pillowcases cause less friction — reducing both skin crease wrinkles and hair breakage overnight.",
  },
  {
    key: "hair_braid_sleep",
    title: "Loosely Braid Hair Before Sleep",
    icon: "Spiral",
    category: "sleep",
    duration_minutes: 3,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Loosely braid or tie your hair before sleeping to reduce tangling and friction-caused breakage.",
  },
  {
    key: "sleep_8hrs",
    title: "Aim for 8 Hours Sleep",
    icon: "Moon",
    category: "sleep",
    duration_minutes: 480,
    is_premium: false,
    applicable_to: ["face", "hair", "both"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: null,
    description: "Commit to sleeping at least 8 hours tonight. Growth hormones peak during deep sleep — critical for repair.",
  },
  {
    key: "castor_oil_brows",
    title: "Castor Oil on Brows & Lashes",
    icon: "Eye",
    category: "sleep",
    duration_minutes: 2,
    is_premium: true,
    applicable_to: ["face", "hair"],
    skin_types: ["all"],
    severity: ["mild"],
    season: null,
    description: "Dab a tiny amount of castor oil on eyebrows and eyelash line before sleeping to promote growth.",
  },
  {
    key: "overnight_hair_oil",
    title: "Overnight Hair Oil Treatment",
    icon: "Droplet",
    category: "sleep",
    duration_minutes: 5,
    is_premium: true,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["moderate", "serious"],
    season: "winter",
    description: "Apply warm coconut or olive oil all through hair before sleeping. Wash off in the morning.",
  },
  // ─── LIFESTYLE ───
  {
    key: "wipe_sweat",
    title: "Wipe Sweat Immediately",
    icon: "Swatches",
    category: "lifestyle",
    duration_minutes: 0,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["oily", "combination"],
    severity: ["mild", "moderate", "serious"],
    season: "summer",
    description: "Always pat (don't wipe) sweat off your face with a clean tissue. Sweat left to dry clogs pores.",
  },
  {
    key: "clean_spectacles",
    title: "Clean Spectacles Daily",
    icon: "Eyeglasses",
    category: "lifestyle",
    duration_minutes: 2,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Wipe your glasses frames and nose pads with a damp cloth daily — they touch your face and carry bacteria.",
  },
  {
    key: "no_face_touch",
    title: "Don't Touch Your Face Today",
    icon: "HandStop",
    category: "lifestyle",
    duration_minutes: 0,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: null,
    description: "Consciously avoid touching your face today. Hands carry bacteria that cause breakouts.",
  },
  {
    key: "phone_screen_clean",
    title: "Clean Your Phone Screen",
    icon: "DeviceMobile",
    category: "lifestyle",
    duration_minutes: 2,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["oily", "combination"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Wipe your phone screen with an antibacterial wipe. Your phone screen touches your cheek during calls.",
  },
  {
    key: "helmet_hygiene",
    title: "Clean Helmet Padding",
    icon: "Shield",
    category: "lifestyle",
    duration_minutes: 10,
    is_premium: false,
    applicable_to: ["face", "hair"],
    skin_types: ["all"],
    severity: ["moderate", "serious"],
    season: "summer",
    description: "Wipe the inside of your helmet with a damp cloth. Sweat buildup on helmet padding causes scalp issues.",
  },
  {
    key: "clean_hairbrush",
    title: "Clean Your Hairbrush",
    icon: "Comb",
    category: "lifestyle",
    duration_minutes: 5,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Remove hair from your brush and wash the base with mild shampoo. Dirty brushes redistribute oil and buildup.",
  },
  {
    key: "avoid_heat_styling",
    title: "Skip Heat Styling Today",
    icon: "ThermometerHot",
    category: "lifestyle",
    duration_minutes: 0,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: null,
    description: "Avoid blow dryers, flat irons, and curlers today. Heat damages hair cuticles and causes breakage.",
  },
  {
    key: "loose_hairstyle",
    title: "Wear Hair Loose Today",
    icon: "Wind",
    category: "lifestyle",
    duration_minutes: 0,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Avoid tight ponytails or buns today. Constant tension on hair follicles causes traction hair loss.",
  },
  {
    key: "yoga_10min",
    title: "10 Minutes of Yoga/Breathing",
    icon: "Person",
    category: "lifestyle",
    duration_minutes: 10,
    is_premium: false,
    applicable_to: ["face", "hair", "both"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: null,
    description: "Do 10 minutes of pranayama or yoga. Chronic stress elevates cortisol which triggers hair fall and breakouts.",
  },
  {
    key: "sunscreen_apply",
    title: "Apply Sunscreen (SPF 30+)",
    icon: "Sun",
    category: "lifestyle",
    duration_minutes: 3,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: "summer",
    description: "Apply a broad-spectrum SPF 30 or higher sunscreen 20 minutes before stepping out. Non-negotiable for skin health.",
  },
  {
    key: "cold_water_hair_rinse",
    title: "Cold Water Final Hair Rinse",
    icon: "Snowflake",
    category: "lifestyle",
    duration_minutes: 2,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild"],
    season: null,
    description: "End your hair wash with a 30-second cold water rinse. It seals the cuticle and adds shine.",
  },
  // ─── MONSOON SEASONAL ───
  {
    key: "anti_fungal_scalp",
    title: "Anti-Fungal Scalp Rinse",
    icon: "ShieldCheck",
    category: "morning",
    duration_minutes: 5,
    is_premium: true,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["moderate", "serious"],
    season: "monsoon",
    description: "Add 2 drops of tea tree oil to your shampoo. Monsoon humidity encourages fungal scalp infections.",
  },
  {
    key: "dry_hair_monsoon",
    title: "Dry Hair Completely",
    icon: "Wind",
    category: "lifestyle",
    duration_minutes: 10,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild", "moderate", "serious"],
    season: "monsoon",
    description: "Never step out or sleep with wet hair during monsoon. Wet scalp in humidity is a breeding ground for dandruff.",
  },
  {
    key: "neem_face_wash_monsoon",
    title: "Neem Face Wash (Monsoon)",
    icon: "Leaf",
    category: "morning",
    duration_minutes: 5,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["oily", "combination"],
    severity: ["moderate", "serious"],
    season: "monsoon",
    description: "Use a neem-based face wash twice today. Monsoon air carries more pollutants and bacteria.",
  },
  {
    key: "light_moisturiser_monsoon",
    title: "Switch to Light Moisturiser",
    icon: "Droplet",
    category: "morning",
    duration_minutes: 3,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["oily", "combination"],
    severity: ["mild", "moderate"],
    season: "monsoon",
    description: "Swap heavy creams for a water-based gel moisturiser during monsoon. Heavy creams clog pores in humidity.",
  },
  // ─── WINTER SEASONAL ───
  {
    key: "deep_moisturise_winter",
    title: "Deep Moisturise Routine",
    icon: "Droplets",
    category: "morning",
    duration_minutes: 5,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["dry", "normal"],
    severity: ["mild", "moderate"],
    season: "winter",
    description: "Apply a rich cream or facial oil after your serum in winter. Cold air strips the skin's moisture barrier.",
  },
  {
    key: "oil_hair_winter",
    title: "Warm Oil Before Bath (Winter)",
    icon: "ThermometerHot",
    category: "morning",
    duration_minutes: 20,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: "winter",
    description: "Warm coconut or sesame oil and massage into scalp 30 minutes before bathing. Prevents winter dryness.",
  },
  {
    key: "humidifier_night",
    title: "Use a Humidifier at Night",
    icon: "CloudFog",
    category: "sleep",
    duration_minutes: 0,
    is_premium: true,
    applicable_to: ["face", "hair", "both"],
    skin_types: ["dry", "normal"],
    severity: ["mild"],
    season: "winter",
    description: "Run a humidifier while sleeping in winter. Dry indoor air depletes skin moisture overnight.",
  },
  // ─── ADDITIONAL FACE ───
  {
    key: "vitamin_c_serum",
    title: "Vitamin C Serum Morning",
    icon: "Sun",
    category: "morning",
    duration_minutes: 3,
    is_premium: true,
    applicable_to: ["face"],
    skin_types: ["dry", "normal", "combination"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Apply 2–3 drops of vitamin C serum before sunscreen in the morning to brighten and protect.",
  },
  {
    key: "hyaluronic_acid",
    title: "Hyaluronic Acid Hydration",
    icon: "Droplet",
    category: "evening",
    duration_minutes: 3,
    is_premium: true,
    applicable_to: ["face"],
    skin_types: ["dry", "normal"],
    severity: ["mild"],
    season: null,
    description: "Apply HA serum on damp skin in the evening. It draws in moisture and plumps the skin barrier.",
  },
  {
    key: "face_yoga",
    title: "5 Minute Face Yoga",
    icon: "Smiley",
    category: "morning",
    duration_minutes: 5,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["all"],
    severity: ["mild"],
    season: null,
    description: "Do cheek puffs, jaw releases, and brow raises for 5 minutes to tone facial muscles.",
  },
  {
    key: "steam_pore_cleanse",
    title: "Steam Pore Cleanse",
    icon: "CloudFog",
    category: "evening",
    duration_minutes: 10,
    is_premium: false,
    applicable_to: ["face"],
    skin_types: ["oily", "combination"],
    severity: ["moderate", "serious"],
    season: null,
    description: "Boil water and steam your face 25cm away for 10 minutes. Opens pores for better cleansing.",
  },
  {
    key: "salicylic_toner",
    title: "Salicylic Acid Toner",
    icon: "TestTube",
    category: "evening",
    duration_minutes: 3,
    is_premium: true,
    applicable_to: ["face"],
    skin_types: ["oily", "combination"],
    severity: ["moderate", "serious"],
    season: null,
    description: "Apply a BHA toner on a cotton pad after cleansing to keep pores clear and reduce blackheads.",
  },
  // ─── ADDITIONAL HAIR ───
  {
    key: "derma_roller_scalp",
    title: "Derma Roller Scalp Session",
    icon: "CircleWavy",
    category: "morning",
    duration_minutes: 10,
    is_premium: true,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["serious"],
    season: null,
    description: "Use a 0.5mm derma roller on scalp twice weekly. Micro-needling stimulates follicle activity.",
  },
  {
    key: "green_tea_hair_rinse",
    title: "Green Tea Hair Rinse",
    icon: "Leaf",
    category: "morning",
    duration_minutes: 10,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Brew and cool green tea, use as a final hair rinse after shampooing. DHT-blocking antioxidants.",
  },
  {
    key: "neem_oil_scalp",
    title: "Neem Oil Scalp Treatment",
    icon: "Leaf",
    category: "morning",
    duration_minutes: 20,
    is_premium: true,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["moderate", "serious"],
    season: null,
    description: "Mix 5 drops neem oil with 2 tbsp carrier oil. Apply to scalp, leave 20 min, then wash out.",
  },
  {
    key: "wide_tooth_comb",
    title: "Use Wide-Tooth Comb Only",
    icon: "Comb",
    category: "lifestyle",
    duration_minutes: 3,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Switch to a wide-tooth comb today, especially when hair is wet. Reduces breakage significantly.",
  },
  {
    key: "protein_hair_mask",
    title: "DIY Protein Hair Mask",
    icon: "Egg",
    category: "morning",
    duration_minutes: 30,
    is_premium: true,
    applicable_to: ["hair"],
    skin_types: ["all"],
    severity: ["moderate", "serious"],
    season: null,
    description: "Blend egg, yoghurt and honey into a mask. Apply from root to tip, leave 30 minutes then rinse.",
  },
  {
    key: "reduce_shampoo_freq",
    title: "Skip One Shampoo This Week",
    icon: "ArrowDown",
    category: "lifestyle",
    duration_minutes: 0,
    is_premium: false,
    applicable_to: ["hair"],
    skin_types: ["dry", "normal"],
    severity: ["mild", "moderate"],
    season: null,
    description: "Over-washing strips natural scalp oils. If you shampoo daily, skip one day and use dry shampoo.",
  },
];

type ScanType = "face" | "hair";
type SkinType = "oily" | "dry" | "combination" | "normal";
type Severity = "mild" | "moderate" | "serious";
type Season = "monsoon" | "summer" | "winter";

function getCurrentSeason(): Season | null {
  const month = new Date().getMonth() + 1; // 1-12
  if (month >= 6 && month <= 9) return "monsoon";
  if (month >= 3 && month <= 5) return "summer";
  if (month === 12 || month <= 2) return "winter";
  return null;
}

export function getPersonalisedRemedies(
  scanType: ScanType,
  severity: Severity,
  skinType: SkinType | null,
  _remedyCategories: string[],
): Remedy[] {
  const season = getCurrentSeason();

  const filtered = REMEDY_LIBRARY.filter((r) => {
    const typeMatch =
      r.applicable_to.includes(scanType) || r.applicable_to.includes("both");
    const severityMatch = r.severity.includes(severity);
    const skinMatch =
      !skinType ||
      r.skin_types.includes("all") ||
      r.skin_types.includes(skinType);
    const seasonMatch = r.season === null || r.season === season;
    return typeMatch && severityMatch && skinMatch && seasonMatch;
  });

  return filtered.slice(0, 8);
}

export function generateDailyTasks(
  skinType: SkinType | null,
  concern: "skin" | "hair" | "both",
  dayNumber: number,
  isSubscribed: boolean,
): Remedy[] {
  const season = getCurrentSeason();

  const filterForConcern = (r: Remedy): boolean => {
    if (concern === "skin")
      return r.applicable_to.includes("face") || r.applicable_to.includes("both");
    if (concern === "hair")
      return r.applicable_to.includes("hair") || r.applicable_to.includes("both");
    return true;
  };

  const filterSkin = (r: Remedy): boolean =>
    !skinType || r.skin_types.includes("all") || r.skin_types.includes(skinType);

  const filterSeason = (r: Remedy): boolean =>
    r.season === null || r.season === season;

  const pickOne = (category: Remedy["category"], premiumOk: boolean): Remedy | undefined => {
    const pool = REMEDY_LIBRARY.filter(
      (r) =>
        r.category === category &&
        filterForConcern(r) &&
        filterSkin(r) &&
        filterSeason(r) &&
        (premiumOk ? true : !r.is_premium),
    );
    if (!pool.length) return undefined;
    return pool[dayNumber % pool.length];
  };

  const tasks: Remedy[] = [];
  const seen = new Set<string>();
  const add = (r: Remedy | undefined) => {
    if (r && !seen.has(r.key)) {
      seen.add(r.key);
      tasks.push(r);
    }
  };

  if (isSubscribed) {
    add(pickOne("morning", true));
    add(pickOne("morning", true));
    add(pickOne("diet", true));
    add(pickOne("diet", true));
    add(pickOne("evening", true));
    add(pickOne("evening", true));
    add(pickOne("sleep", true));
    add(pickOne("lifestyle", true));
  } else {
    add(pickOne("morning", false));
    add(pickOne("diet", false));
    add(pickOne("evening", false));
  }

  return tasks;
}
